// Code generated by protoc-gen-go. DO NOT EDIT.
// source: B.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConfigPushCall struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Environment          string   `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	Params               []byte   `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigPushCall) Reset()         { *m = ConfigPushCall{} }
func (m *ConfigPushCall) String() string { return proto.CompactTextString(m) }
func (*ConfigPushCall) ProtoMessage()    {}
func (*ConfigPushCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_aec3506d261c51fe, []int{0}
}

func (m *ConfigPushCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigPushCall.Unmarshal(m, b)
}
func (m *ConfigPushCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigPushCall.Marshal(b, m, deterministic)
}
func (m *ConfigPushCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigPushCall.Merge(m, src)
}
func (m *ConfigPushCall) XXX_Size() int {
	return xxx_messageInfo_ConfigPushCall.Size(m)
}
func (m *ConfigPushCall) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigPushCall.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigPushCall proto.InternalMessageInfo

func (m *ConfigPushCall) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ConfigPushCall) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *ConfigPushCall) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

type ConfigPushBack struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigPushBack) Reset()         { *m = ConfigPushBack{} }
func (m *ConfigPushBack) String() string { return proto.CompactTextString(m) }
func (*ConfigPushBack) ProtoMessage()    {}
func (*ConfigPushBack) Descriptor() ([]byte, []int) {
	return fileDescriptor_aec3506d261c51fe, []int{1}
}

func (m *ConfigPushBack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigPushBack.Unmarshal(m, b)
}
func (m *ConfigPushBack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigPushBack.Marshal(b, m, deterministic)
}
func (m *ConfigPushBack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigPushBack.Merge(m, src)
}
func (m *ConfigPushBack) XXX_Size() int {
	return xxx_messageInfo_ConfigPushBack.Size(m)
}
func (m *ConfigPushBack) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigPushBack.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigPushBack proto.InternalMessageInfo

func (m *ConfigPushBack) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type ConfigPullCall struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Environment          string   `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigPullCall) Reset()         { *m = ConfigPullCall{} }
func (m *ConfigPullCall) String() string { return proto.CompactTextString(m) }
func (*ConfigPullCall) ProtoMessage()    {}
func (*ConfigPullCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_aec3506d261c51fe, []int{2}
}

func (m *ConfigPullCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigPullCall.Unmarshal(m, b)
}
func (m *ConfigPullCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigPullCall.Marshal(b, m, deterministic)
}
func (m *ConfigPullCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigPullCall.Merge(m, src)
}
func (m *ConfigPullCall) XXX_Size() int {
	return xxx_messageInfo_ConfigPullCall.Size(m)
}
func (m *ConfigPullCall) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigPullCall.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigPullCall proto.InternalMessageInfo

func (m *ConfigPullCall) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ConfigPullCall) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

type ConfigPullBack struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Params               []byte   `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigPullBack) Reset()         { *m = ConfigPullBack{} }
func (m *ConfigPullBack) String() string { return proto.CompactTextString(m) }
func (*ConfigPullBack) ProtoMessage()    {}
func (*ConfigPullBack) Descriptor() ([]byte, []int) {
	return fileDescriptor_aec3506d261c51fe, []int{3}
}

func (m *ConfigPullBack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigPullBack.Unmarshal(m, b)
}
func (m *ConfigPullBack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigPullBack.Marshal(b, m, deterministic)
}
func (m *ConfigPullBack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigPullBack.Merge(m, src)
}
func (m *ConfigPullBack) XXX_Size() int {
	return xxx_messageInfo_ConfigPullBack.Size(m)
}
func (m *ConfigPullBack) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigPullBack.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigPullBack proto.InternalMessageInfo

func (m *ConfigPullBack) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ConfigPullBack) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

func init() {
	proto.RegisterType((*ConfigPushCall)(nil), "pb.ConfigPushCall")
	proto.RegisterType((*ConfigPushBack)(nil), "pb.ConfigPushBack")
	proto.RegisterType((*ConfigPullCall)(nil), "pb.ConfigPullCall")
	proto.RegisterType((*ConfigPullBack)(nil), "pb.ConfigPullBack")
}

func init() { proto.RegisterFile("B.proto", fileDescriptor_aec3506d261c51fe) }

var fileDescriptor_aec3506d261c51fe = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x62, 0x77, 0xd2, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x8a, 0xe2, 0xe2, 0x73, 0xce, 0xcf, 0x4b, 0xcb,
	0x4c, 0x0f, 0x28, 0x2d, 0xce, 0x70, 0x4e, 0xcc, 0xc9, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x4c, 0x11, 0x52, 0xe0, 0xe2, 0x4e, 0xcd, 0x2b,
	0xcb, 0x2c, 0xca, 0xcf, 0xcb, 0x4d, 0xcd, 0x2b, 0x91, 0x60, 0x02, 0x4b, 0x20, 0x0b, 0x09, 0x89,
	0x71, 0xb1, 0x15, 0x24, 0x16, 0x25, 0xe6, 0x16, 0x4b, 0x30, 0x2b, 0x30, 0x6a, 0xf0, 0x04, 0x41,
	0x79, 0x4a, 0x2a, 0xc8, 0x66, 0x3b, 0x25, 0x26, 0x67, 0x0b, 0x09, 0x71, 0xb1, 0x24, 0xe7, 0xa7,
	0xa4, 0x82, 0x4d, 0x67, 0x0e, 0x02, 0xb3, 0x95, 0x9c, 0x10, 0xaa, 0x72, 0x72, 0xc8, 0x73, 0x81,
	0x92, 0x0d, 0xb2, 0x19, 0xb8, 0x6c, 0x42, 0x72, 0x27, 0x13, 0xb2, 0x3b, 0x8d, 0x2a, 0xb9, 0x78,
	0x21, 0xba, 0x83, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0x8c, 0xb9, 0xd8, 0x41, 0x4e, 0x0e,
	0x0a, 0x70, 0x16, 0x12, 0xd2, 0x2b, 0x48, 0xd2, 0x43, 0x0d, 0x21, 0x29, 0x34, 0x31, 0x90, 0x7d,
	0x4a, 0x0c, 0x10, 0x4d, 0x39, 0x39, 0x18, 0x9a, 0x20, 0x9e, 0x92, 0x42, 0x13, 0x83, 0x68, 0x4a,
	0x62, 0x03, 0xc7, 0x84, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x9e, 0x6a, 0x9e, 0x94, 0x01,
	0x00, 0x00,
}
