// Code generated by protoc-gen-go.
// source: Be.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	Be.proto
	He.proto
	Li.proto
	general.proto

It has these top-level messages:
	AssetTemplateCall
	AssetCloudCall
	AssetMsgBack
	AAAGenerateTokenCall
	AAAGenerateTokenBack
	AAATokenCall
	AAATokenBack
	CloudAPICall
	CloudAPIBack
	GeneralMsgCall
	GeneralMsgBack
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AssetTemplateCall struct {
	Id    string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name  string            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Param map[string]string `protobuf:"bytes,3,rep,name=param" json:"param,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *AssetTemplateCall) Reset()                    { *m = AssetTemplateCall{} }
func (m *AssetTemplateCall) String() string            { return proto.CompactTextString(m) }
func (*AssetTemplateCall) ProtoMessage()               {}
func (*AssetTemplateCall) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AssetTemplateCall) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AssetTemplateCall) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AssetTemplateCall) GetParam() map[string]string {
	if m != nil {
		return m.Param
	}
	return nil
}

type AssetCloudCall struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Cloud string `protobuf:"bytes,2,opt,name=cloud" json:"cloud,omitempty"`
	Data  []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *AssetCloudCall) Reset()                    { *m = AssetCloudCall{} }
func (m *AssetCloudCall) String() string            { return proto.CompactTextString(m) }
func (*AssetCloudCall) ProtoMessage()               {}
func (*AssetCloudCall) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AssetCloudCall) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AssetCloudCall) GetCloud() string {
	if m != nil {
		return m.Cloud
	}
	return ""
}

func (m *AssetCloudCall) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type AssetMsgBack struct {
	Code int64  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *AssetMsgBack) Reset()                    { *m = AssetMsgBack{} }
func (m *AssetMsgBack) String() string            { return proto.CompactTextString(m) }
func (*AssetMsgBack) ProtoMessage()               {}
func (*AssetMsgBack) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AssetMsgBack) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AssetMsgBack) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*AssetTemplateCall)(nil), "pb.AssetTemplateCall")
	proto.RegisterType((*AssetCloudCall)(nil), "pb.AssetCloudCall")
	proto.RegisterType((*AssetMsgBack)(nil), "pb.AssetMsgBack")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Asset service

type AssetClient interface {
	AddTemplateRPC(ctx context.Context, in *AssetTemplateCall, opts ...grpc.CallOption) (*AssetMsgBack, error)
	AddAssetRPC(ctx context.Context, in *AssetCloudCall, opts ...grpc.CallOption) (*AssetMsgBack, error)
}

type assetClient struct {
	cc *grpc.ClientConn
}

func NewAssetClient(cc *grpc.ClientConn) AssetClient {
	return &assetClient{cc}
}

func (c *assetClient) AddTemplateRPC(ctx context.Context, in *AssetTemplateCall, opts ...grpc.CallOption) (*AssetMsgBack, error) {
	out := new(AssetMsgBack)
	err := grpc.Invoke(ctx, "/pb.Asset/AddTemplateRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetClient) AddAssetRPC(ctx context.Context, in *AssetCloudCall, opts ...grpc.CallOption) (*AssetMsgBack, error) {
	out := new(AssetMsgBack)
	err := grpc.Invoke(ctx, "/pb.Asset/AddAssetRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Asset service

type AssetServer interface {
	AddTemplateRPC(context.Context, *AssetTemplateCall) (*AssetMsgBack, error)
	AddAssetRPC(context.Context, *AssetCloudCall) (*AssetMsgBack, error)
}

func RegisterAssetServer(s *grpc.Server, srv AssetServer) {
	s.RegisterService(&_Asset_serviceDesc, srv)
}

func _Asset_AddTemplateRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetTemplateCall)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServer).AddTemplateRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Asset/AddTemplateRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServer).AddTemplateRPC(ctx, req.(*AssetTemplateCall))
	}
	return interceptor(ctx, in, info, handler)
}

func _Asset_AddAssetRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetCloudCall)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServer).AddAssetRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Asset/AddAssetRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServer).AddAssetRPC(ctx, req.(*AssetCloudCall))
	}
	return interceptor(ctx, in, info, handler)
}

var _Asset_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Asset",
	HandlerType: (*AssetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTemplateRPC",
			Handler:    _Asset_AddTemplateRPC_Handler,
		},
		{
			MethodName: "AddAssetRPC",
			Handler:    _Asset_AddAssetRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Be.proto",
}

func init() { proto.RegisterFile("Be.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xcd, 0x6a, 0x83, 0x40,
	0x10, 0xae, 0x5a, 0x4b, 0x3b, 0x09, 0x92, 0x0e, 0x29, 0x48, 0x4e, 0xe2, 0xc9, 0x93, 0x87, 0xf4,
	0x87, 0xd0, 0x9e, 0x8c, 0xf4, 0x52, 0x28, 0x84, 0xa5, 0x2f, 0xb0, 0xba, 0x4b, 0x08, 0x59, 0xe3,
	0xa2, 0x9b, 0x42, 0xe8, 0x13, 0xf5, 0x2d, 0xcb, 0x4e, 0xd4, 0x1e, 0xe2, 0xed, 0x9b, 0x6f, 0xbf,
	0x9f, 0x19, 0x16, 0x6e, 0xd7, 0x32, 0xd5, 0x4d, 0x6d, 0x6a, 0x74, 0x75, 0x11, 0xff, 0x3a, 0x70,
	0x9f, 0xb5, 0xad, 0x34, 0x5f, 0xb2, 0xd2, 0x8a, 0x1b, 0x99, 0x73, 0xa5, 0x30, 0x00, 0x77, 0x27,
	0x42, 0x27, 0x72, 0x92, 0x3b, 0xe6, 0xee, 0x04, 0x22, 0x5c, 0x1f, 0x78, 0x25, 0x43, 0x97, 0x18,
	0xc2, 0xf8, 0x02, 0xbe, 0xe6, 0x0d, 0xaf, 0x42, 0x2f, 0xf2, 0x92, 0xc9, 0x32, 0x4a, 0x75, 0x91,
	0x5e, 0x24, 0xa5, 0x1b, 0x2b, 0x79, 0x3f, 0x98, 0xe6, 0xc4, 0xce, 0xf2, 0xc5, 0x0a, 0xe0, 0x9f,
	0xc4, 0x19, 0x78, 0x7b, 0x79, 0xea, 0xaa, 0x2c, 0xc4, 0x39, 0xf8, 0xdf, 0x5c, 0x1d, 0xfb, 0xb2,
	0xf3, 0xf0, 0xea, 0xae, 0x9c, 0xf8, 0x03, 0x02, 0x2a, 0xc8, 0x55, 0x7d, 0x14, 0xa3, 0x7b, 0xce,
	0xc1, 0x2f, 0xed, 0x63, 0xef, 0xa5, 0xc1, 0x6e, 0x2f, 0xb8, 0xe1, 0xa1, 0x17, 0x39, 0xc9, 0x94,
	0x11, 0x8e, 0x9f, 0x60, 0x4a, 0x59, 0x9f, 0xed, 0x76, 0xcd, 0xcb, 0xbd, 0xd5, 0x94, 0xb5, 0x90,
	0x94, 0xe5, 0x31, 0xc2, 0x76, 0xb7, 0xaa, 0xdd, 0x76, 0x59, 0x16, 0x2e, 0x7f, 0xc0, 0x27, 0x17,
	0xbe, 0x41, 0x90, 0x09, 0xd1, 0x5f, 0xca, 0x36, 0x39, 0x3e, 0x8c, 0xde, 0xbf, 0x98, 0x0d, 0x74,
	0xd7, 0x14, 0x5f, 0xe1, 0x33, 0x4c, 0x32, 0x21, 0x88, 0xb4, 0x4e, 0x1c, 0x24, 0xc3, 0x61, 0x63,
	0xb6, 0xe2, 0x86, 0x7e, 0xed, 0xf1, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x57, 0xcf, 0x6e, 0xc1,
	0x01, 0x00, 0x00,
}
