// Code generated by protoc-gen-go.
// source: C.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type HookCreateCall struct {
	Hooktype string `protobuf:"bytes,1,opt,name=hooktype" json:"hooktype,omitempty"`
	Rename   bool   `protobuf:"varint,2,opt,name=rename" json:"rename,omitempty"`
}

func (m *HookCreateCall) Reset()                    { *m = HookCreateCall{} }
func (m *HookCreateCall) String() string            { return proto.CompactTextString(m) }
func (*HookCreateCall) ProtoMessage()               {}
func (*HookCreateCall) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *HookCreateCall) GetHooktype() string {
	if m != nil {
		return m.Hooktype
	}
	return ""
}

func (m *HookCreateCall) GetRename() bool {
	if m != nil {
		return m.Rename
	}
	return false
}

type HookCreateBack struct {
	Code     int64  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Hookname string `protobuf:"bytes,2,opt,name=hookname" json:"hookname,omitempty"`
}

func (m *HookCreateBack) Reset()                    { *m = HookCreateBack{} }
func (m *HookCreateBack) String() string            { return proto.CompactTextString(m) }
func (*HookCreateBack) ProtoMessage()               {}
func (*HookCreateBack) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *HookCreateBack) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HookCreateBack) GetHookname() string {
	if m != nil {
		return m.Hookname
	}
	return ""
}

type HookQueryCall struct {
	Hookname string `protobuf:"bytes,1,opt,name=hookname" json:"hookname,omitempty"`
}

func (m *HookQueryCall) Reset()                    { *m = HookQueryCall{} }
func (m *HookQueryCall) String() string            { return proto.CompactTextString(m) }
func (*HookQueryCall) ProtoMessage()               {}
func (*HookQueryCall) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *HookQueryCall) GetHookname() string {
	if m != nil {
		return m.Hookname
	}
	return ""
}

type HookQueryBack struct {
	Code   int64  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Hookid string `protobuf:"bytes,2,opt,name=hookid" json:"hookid,omitempty"`
}

func (m *HookQueryBack) Reset()                    { *m = HookQueryBack{} }
func (m *HookQueryBack) String() string            { return proto.CompactTextString(m) }
func (*HookQueryBack) ProtoMessage()               {}
func (*HookQueryBack) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *HookQueryBack) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HookQueryBack) GetHookid() string {
	if m != nil {
		return m.Hookid
	}
	return ""
}

type HookReceiveCall struct {
	Hookname string `protobuf:"bytes,1,opt,name=hookname" json:"hookname,omitempty"`
	Payload  []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *HookReceiveCall) Reset()                    { *m = HookReceiveCall{} }
func (m *HookReceiveCall) String() string            { return proto.CompactTextString(m) }
func (*HookReceiveCall) ProtoMessage()               {}
func (*HookReceiveCall) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *HookReceiveCall) GetHookname() string {
	if m != nil {
		return m.Hookname
	}
	return ""
}

func (m *HookReceiveCall) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type HookReceiveBack struct {
	Code   int64  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Hookid string `protobuf:"bytes,2,opt,name=hookid" json:"hookid,omitempty"`
	Params []byte `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
}

func (m *HookReceiveBack) Reset()                    { *m = HookReceiveBack{} }
func (m *HookReceiveBack) String() string            { return proto.CompactTextString(m) }
func (*HookReceiveBack) ProtoMessage()               {}
func (*HookReceiveBack) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *HookReceiveBack) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HookReceiveBack) GetHookid() string {
	if m != nil {
		return m.Hookid
	}
	return ""
}

func (m *HookReceiveBack) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

func init() {
	proto.RegisterType((*HookCreateCall)(nil), "pb.HookCreateCall")
	proto.RegisterType((*HookCreateBack)(nil), "pb.HookCreateBack")
	proto.RegisterType((*HookQueryCall)(nil), "pb.HookQueryCall")
	proto.RegisterType((*HookQueryBack)(nil), "pb.HookQueryBack")
	proto.RegisterType((*HookReceiveCall)(nil), "pb.HookReceiveCall")
	proto.RegisterType((*HookReceiveBack)(nil), "pb.HookReceiveBack")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for HookService service

type HookServiceClient interface {
	CreateRPC(ctx context.Context, in *HookCreateCall, opts ...grpc.CallOption) (*HookCreateBack, error)
	QueryRPC(ctx context.Context, in *HookQueryCall, opts ...grpc.CallOption) (*HookQueryBack, error)
	ReceiveRPC(ctx context.Context, in *HookReceiveCall, opts ...grpc.CallOption) (*HookReceiveBack, error)
}

type hookServiceClient struct {
	cc *grpc.ClientConn
}

func NewHookServiceClient(cc *grpc.ClientConn) HookServiceClient {
	return &hookServiceClient{cc}
}

func (c *hookServiceClient) CreateRPC(ctx context.Context, in *HookCreateCall, opts ...grpc.CallOption) (*HookCreateBack, error) {
	out := new(HookCreateBack)
	err := grpc.Invoke(ctx, "/pb.HookService/CreateRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hookServiceClient) QueryRPC(ctx context.Context, in *HookQueryCall, opts ...grpc.CallOption) (*HookQueryBack, error) {
	out := new(HookQueryBack)
	err := grpc.Invoke(ctx, "/pb.HookService/QueryRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hookServiceClient) ReceiveRPC(ctx context.Context, in *HookReceiveCall, opts ...grpc.CallOption) (*HookReceiveBack, error) {
	out := new(HookReceiveBack)
	err := grpc.Invoke(ctx, "/pb.HookService/ReceiveRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HookService service

type HookServiceServer interface {
	CreateRPC(context.Context, *HookCreateCall) (*HookCreateBack, error)
	QueryRPC(context.Context, *HookQueryCall) (*HookQueryBack, error)
	ReceiveRPC(context.Context, *HookReceiveCall) (*HookReceiveBack, error)
}

func RegisterHookServiceServer(s *grpc.Server, srv HookServiceServer) {
	s.RegisterService(&_HookService_serviceDesc, srv)
}

func _HookService_CreateRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HookCreateCall)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HookServiceServer).CreateRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HookService/CreateRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HookServiceServer).CreateRPC(ctx, req.(*HookCreateCall))
	}
	return interceptor(ctx, in, info, handler)
}

func _HookService_QueryRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HookQueryCall)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HookServiceServer).QueryRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HookService/QueryRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HookServiceServer).QueryRPC(ctx, req.(*HookQueryCall))
	}
	return interceptor(ctx, in, info, handler)
}

func _HookService_ReceiveRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HookReceiveCall)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HookServiceServer).ReceiveRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HookService/ReceiveRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HookServiceServer).ReceiveRPC(ctx, req.(*HookReceiveCall))
	}
	return interceptor(ctx, in, info, handler)
}

var _HookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.HookService",
	HandlerType: (*HookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRPC",
			Handler:    _HookService_CreateRPC_Handler,
		},
		{
			MethodName: "QueryRPC",
			Handler:    _HookService_QueryRPC_Handler,
		},
		{
			MethodName: "ReceiveRPC",
			Handler:    _HookService_ReceiveRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "C.proto",
}

func init() { proto.RegisterFile("C.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xdd, 0x56, 0xda, 0x74, 0xfc, 0x87, 0x23, 0x94, 0x90, 0x53, 0xd9, 0x53, 0x41, 0xc8,
	0xa1, 0x22, 0x08, 0x5e, 0xc4, 0x08, 0x7a, 0xd4, 0x15, 0x3f, 0xc0, 0x26, 0x1d, 0x30, 0x24, 0x75,
	0x97, 0x35, 0x16, 0xf2, 0xb5, 0xfc, 0x84, 0xb2, 0x9b, 0x4d, 0x48, 0x02, 0x22, 0xde, 0xf2, 0x86,
	0xf7, 0x7e, 0x33, 0x79, 0x09, 0xcc, 0x93, 0x58, 0x1b, 0x55, 0x29, 0x9c, 0xe8, 0x94, 0x3f, 0xc0,
	0xe9, 0x93, 0x52, 0x45, 0x62, 0x48, 0x56, 0x94, 0xc8, 0xb2, 0xc4, 0x08, 0x82, 0x77, 0xa5, 0x8a,
	0xaa, 0xd6, 0x14, 0xb2, 0x15, 0x5b, 0x2f, 0x44, 0xa7, 0x71, 0x09, 0x33, 0x43, 0x1f, 0x72, 0x47,
	0xe1, 0x64, 0xc5, 0xd6, 0x81, 0xf0, 0x8a, 0xdf, 0xf5, 0x29, 0xf7, 0x32, 0x2b, 0x10, 0xe1, 0x30,
	0x53, 0xdb, 0x86, 0x30, 0x15, 0xee, 0xb9, 0x25, 0x77, 0x79, 0x4f, 0x76, 0x84, 0x4b, 0x38, 0xb1,
	0x84, 0x97, 0x2f, 0x32, 0x75, 0xff, 0x0c, 0x67, 0x66, 0x23, 0xf3, 0x6d, 0xcf, 0xfc, 0xeb, 0xb6,
	0x25, 0xcc, 0x6c, 0x20, 0xdf, 0xfa, 0x5d, 0x5e, 0xf1, 0x47, 0x38, 0xb3, 0x61, 0x41, 0x19, 0xe5,
	0x7b, 0xfa, 0x6b, 0x17, 0x86, 0x30, 0xd7, 0xb2, 0x2e, 0x95, 0x6c, 0x38, 0xc7, 0xa2, 0x95, 0xfc,
	0x6d, 0x00, 0xfa, 0xef, 0x1d, 0x76, 0xae, 0xa5, 0x91, 0xbb, 0xcf, 0x70, 0xea, 0xb8, 0x5e, 0x6d,
	0xbe, 0x19, 0x1c, 0x59, 0xee, 0x2b, 0x99, 0x7d, 0x9e, 0x11, 0x5e, 0xc3, 0xa2, 0xe9, 0x55, 0x3c,
	0x27, 0x88, 0xb1, 0x4e, 0xe3, 0xe1, 0x07, 0x8b, 0x46, 0x33, 0x7b, 0x08, 0x3f, 0xc0, 0x0d, 0x04,
	0xae, 0x1f, 0x9b, 0x3a, 0x6f, 0x1d, 0x5d, 0xbd, 0xd1, 0x70, 0xe4, 0x33, 0x37, 0x00, 0xfe, 0x6d,
	0x6c, 0xea, 0xa2, 0xb5, 0xf4, 0xaa, 0x8a, 0xc6, 0xc3, 0x26, 0x99, 0xce, 0xdc, 0x1f, 0x75, 0xf5,
	0x13, 0x00, 0x00, 0xff, 0xff, 0x6c, 0xe1, 0x59, 0x66, 0x5c, 0x02, 0x00, 0x00,
}
