// Code generated by protoc-gen-go.
// source: general.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GeneralMsgIn struct {
	Code int64 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
}

func (m *GeneralMsgIn) Reset()                    { *m = GeneralMsgIn{} }
func (m *GeneralMsgIn) String() string            { return proto.CompactTextString(m) }
func (*GeneralMsgIn) ProtoMessage()               {}
func (*GeneralMsgIn) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *GeneralMsgIn) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type GeneralMsgOut struct {
	Code int64  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *GeneralMsgOut) Reset()                    { *m = GeneralMsgOut{} }
func (m *GeneralMsgOut) String() string            { return proto.CompactTextString(m) }
func (*GeneralMsgOut) ProtoMessage()               {}
func (*GeneralMsgOut) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *GeneralMsgOut) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GeneralMsgOut) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*GeneralMsgIn)(nil), "pb.GeneralMsgIn")
	proto.RegisterType((*GeneralMsgOut)(nil), "pb.GeneralMsgOut")
}

func init() { proto.RegisterFile("general.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4f, 0xcd, 0x4b,
	0x2d, 0x4a, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x52, 0xe2,
	0xe2, 0x71, 0x87, 0x08, 0xfa, 0x16, 0xa7, 0x7b, 0xe6, 0x09, 0x09, 0x71, 0xb1, 0x24, 0xe7, 0xa7,
	0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x81, 0xd9, 0x4a, 0xa6, 0x5c, 0xbc, 0x08, 0x35,
	0xfe, 0xa5, 0x25, 0xd8, 0x14, 0x09, 0x09, 0x70, 0x31, 0xe7, 0x16, 0xa7, 0x4b, 0x30, 0x29, 0x30,
	0x6a, 0x70, 0x06, 0x81, 0x98, 0x49, 0x6c, 0x60, 0x5b, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x44, 0x9f, 0x1e, 0x02, 0x76, 0x00, 0x00, 0x00,
}
