// Code generated by protoc-gen-go.
// source: He.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type AAAGenerateTokenCall struct {
	Email string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Phone string `protobuf:"bytes,2,opt,name=phone" json:"phone,omitempty"`
}

func (m *AAAGenerateTokenCall) Reset()                    { *m = AAAGenerateTokenCall{} }
func (m *AAAGenerateTokenCall) String() string            { return proto.CompactTextString(m) }
func (*AAAGenerateTokenCall) ProtoMessage()               {}
func (*AAAGenerateTokenCall) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *AAAGenerateTokenCall) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AAAGenerateTokenCall) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type AAAGenerateTokenBack struct {
	Id  string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Key string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *AAAGenerateTokenBack) Reset()                    { *m = AAAGenerateTokenBack{} }
func (m *AAAGenerateTokenBack) String() string            { return proto.CompactTextString(m) }
func (*AAAGenerateTokenBack) ProtoMessage()               {}
func (*AAAGenerateTokenBack) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *AAAGenerateTokenBack) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AAAGenerateTokenBack) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type AAATokenCall struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Signature string `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
}

func (m *AAATokenCall) Reset()                    { *m = AAATokenCall{} }
func (m *AAATokenCall) String() string            { return proto.CompactTextString(m) }
func (*AAATokenCall) ProtoMessage()               {}
func (*AAATokenCall) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *AAATokenCall) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AAATokenCall) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type AAATokenBack struct {
	Valid bool `protobuf:"varint,1,opt,name=Valid" json:"Valid,omitempty"`
}

func (m *AAATokenBack) Reset()                    { *m = AAATokenBack{} }
func (m *AAATokenBack) String() string            { return proto.CompactTextString(m) }
func (*AAATokenBack) ProtoMessage()               {}
func (*AAATokenBack) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *AAATokenBack) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*AAAGenerateTokenCall)(nil), "pb.AAAGenerateTokenCall")
	proto.RegisterType((*AAAGenerateTokenBack)(nil), "pb.AAAGenerateTokenBack")
	proto.RegisterType((*AAATokenCall)(nil), "pb.AAATokenCall")
	proto.RegisterType((*AAATokenBack)(nil), "pb.AAATokenBack")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AAAPublicService service

type AAAPublicServiceClient interface {
	GenerateTokenRPC(ctx context.Context, in *AAAGenerateTokenCall, opts ...grpc.CallOption) (*AAAGenerateTokenBack, error)
}

type aAAPublicServiceClient struct {
	cc *grpc.ClientConn
}

func NewAAAPublicServiceClient(cc *grpc.ClientConn) AAAPublicServiceClient {
	return &aAAPublicServiceClient{cc}
}

func (c *aAAPublicServiceClient) GenerateTokenRPC(ctx context.Context, in *AAAGenerateTokenCall, opts ...grpc.CallOption) (*AAAGenerateTokenBack, error) {
	out := new(AAAGenerateTokenBack)
	err := grpc.Invoke(ctx, "/pb.AAAPublicService/GenerateTokenRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AAAPublicService service

type AAAPublicServiceServer interface {
	GenerateTokenRPC(context.Context, *AAAGenerateTokenCall) (*AAAGenerateTokenBack, error)
}

func RegisterAAAPublicServiceServer(s *grpc.Server, srv AAAPublicServiceServer) {
	s.RegisterService(&_AAAPublicService_serviceDesc, srv)
}

func _AAAPublicService_GenerateTokenRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AAAGenerateTokenCall)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AAAPublicServiceServer).GenerateTokenRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AAAPublicService/GenerateTokenRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AAAPublicServiceServer).GenerateTokenRPC(ctx, req.(*AAAGenerateTokenCall))
	}
	return interceptor(ctx, in, info, handler)
}

var _AAAPublicService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AAAPublicService",
	HandlerType: (*AAAPublicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateTokenRPC",
			Handler:    _AAAPublicService_GenerateTokenRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "He.proto",
}

// Client API for AAAPrivateService service

type AAAPrivateServiceClient interface {
	AuthenticationRPC(ctx context.Context, in *AAATokenCall, opts ...grpc.CallOption) (*AAATokenBack, error)
}

type aAAPrivateServiceClient struct {
	cc *grpc.ClientConn
}

func NewAAAPrivateServiceClient(cc *grpc.ClientConn) AAAPrivateServiceClient {
	return &aAAPrivateServiceClient{cc}
}

func (c *aAAPrivateServiceClient) AuthenticationRPC(ctx context.Context, in *AAATokenCall, opts ...grpc.CallOption) (*AAATokenBack, error) {
	out := new(AAATokenBack)
	err := grpc.Invoke(ctx, "/pb.AAAPrivateService/AuthenticationRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AAAPrivateService service

type AAAPrivateServiceServer interface {
	AuthenticationRPC(context.Context, *AAATokenCall) (*AAATokenBack, error)
}

func RegisterAAAPrivateServiceServer(s *grpc.Server, srv AAAPrivateServiceServer) {
	s.RegisterService(&_AAAPrivateService_serviceDesc, srv)
}

func _AAAPrivateService_AuthenticationRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AAATokenCall)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AAAPrivateServiceServer).AuthenticationRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AAAPrivateService/AuthenticationRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AAAPrivateServiceServer).AuthenticationRPC(ctx, req.(*AAATokenCall))
	}
	return interceptor(ctx, in, info, handler)
}

var _AAAPrivateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AAAPrivateService",
	HandlerType: (*AAAPrivateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthenticationRPC",
			Handler:    _AAAPrivateService_AuthenticationRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "He.proto",
}

func init() { proto.RegisterFile("He.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x3f, 0x4b, 0x03, 0x41,
	0x10, 0xc5, 0xcd, 0x49, 0x24, 0x19, 0x44, 0x2e, 0xcb, 0x15, 0x87, 0x58, 0xc8, 0x62, 0x61, 0x75,
	0x45, 0x6c, 0x14, 0x6c, 0x26, 0x29, 0x4c, 0x25, 0xe1, 0x14, 0x2b, 0x9b, 0xbd, 0xcb, 0x60, 0x86,
	0x5b, 0x77, 0x8f, 0x75, 0x2f, 0xe0, 0xb7, 0x97, 0xfb, 0x13, 0x96, 0x98, 0x74, 0xfb, 0xde, 0xf2,
	0x7e, 0x6f, 0x98, 0x81, 0xc9, 0x8a, 0xb2, 0xda, 0x59, 0x6f, 0x45, 0x54, 0x17, 0x72, 0x01, 0x09,
	0x22, 0xbe, 0x90, 0x21, 0xa7, 0x3c, 0xbd, 0xdb, 0x8a, 0xcc, 0x52, 0x69, 0x2d, 0x12, 0x18, 0xd3,
	0xb7, 0x62, 0x9d, 0x8e, 0x6e, 0x47, 0xf7, 0xd3, 0xbc, 0x17, 0xad, 0x5b, 0x6f, 0xad, 0xa1, 0x34,
	0xea, 0xdd, 0x4e, 0xc8, 0xc7, 0x63, 0xc6, 0x42, 0x95, 0x95, 0xb8, 0x82, 0x88, 0x37, 0x03, 0x20,
	0xe2, 0x8d, 0x88, 0xe1, 0xbc, 0xa2, 0xdf, 0x21, 0xdb, 0x3e, 0xe5, 0x33, 0x5c, 0x22, 0x62, 0x68,
	0xfd, 0x9f, 0xb8, 0x81, 0xe9, 0x0f, 0x7f, 0x19, 0xe5, 0x1b, 0xb7, 0xef, 0x0c, 0x86, 0xbc, 0x0b,
	0xe9, 0xae, 0x2f, 0x81, 0xf1, 0x87, 0xd2, 0x03, 0x60, 0x92, 0xf7, 0x62, 0xfe, 0x09, 0x31, 0x22,
	0xae, 0x9b, 0x42, 0x73, 0xf9, 0x46, 0x6e, 0xc7, 0x25, 0x89, 0x15, 0xc4, 0x07, 0xe3, 0xe6, 0xeb,
	0xa5, 0x48, 0xb3, 0xba, 0xc8, 0x4e, 0xed, 0xe2, 0xfa, 0xe4, 0x4f, 0xdb, 0x28, 0xcf, 0xe6, 0xaf,
	0x30, 0x6b, 0xe9, 0x8e, 0x77, 0xca, 0xd3, 0x1e, 0xff, 0x04, 0x33, 0x6c, 0xfc, 0x96, 0x8c, 0xe7,
	0x52, 0x79, 0xb6, 0x1d, 0x3f, 0x1e, 0x28, 0x81, 0x7b, 0xe0, 0xf4, 0xbc, 0xe2, 0xa2, 0x3b, 0xcd,
	0xc3, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcc, 0xb1, 0x24, 0x00, 0xa6, 0x01, 0x00, 0x00,
}
