// Code generated by protoc-gen-go.
// source: Li.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CloudAPICall struct {
	Service  string            `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	Action   string            `protobuf:"bytes,2,opt,name=action" json:"action,omitempty"`
	Region   string            `protobuf:"bytes,3,opt,name=region" json:"region,omitempty"`
	CloudId  string            `protobuf:"bytes,4,opt,name=cloudId" json:"cloudId,omitempty"`
	CloudKey string            `protobuf:"bytes,5,opt,name=cloudKey" json:"cloudKey,omitempty"`
	Cloud    string            `protobuf:"bytes,6,opt,name=cloud" json:"cloud,omitempty"`
	Params   map[string]string `protobuf:"bytes,7,rep,name=params" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *CloudAPICall) Reset()                    { *m = CloudAPICall{} }
func (m *CloudAPICall) String() string            { return proto.CompactTextString(m) }
func (*CloudAPICall) ProtoMessage()               {}
func (*CloudAPICall) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *CloudAPICall) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *CloudAPICall) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *CloudAPICall) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *CloudAPICall) GetCloudId() string {
	if m != nil {
		return m.CloudId
	}
	return ""
}

func (m *CloudAPICall) GetCloudKey() string {
	if m != nil {
		return m.CloudKey
	}
	return ""
}

func (m *CloudAPICall) GetCloud() string {
	if m != nil {
		return m.Cloud
	}
	return ""
}

func (m *CloudAPICall) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

type CloudAPIBack struct {
	Code int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *CloudAPIBack) Reset()                    { *m = CloudAPIBack{} }
func (m *CloudAPIBack) String() string            { return proto.CompactTextString(m) }
func (*CloudAPIBack) ProtoMessage()               {}
func (*CloudAPIBack) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *CloudAPIBack) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CloudAPIBack) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *CloudAPIBack) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type CloudTokenCall struct {
	Cloud      string `protobuf:"bytes,1,opt,name=cloud" json:"cloud,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Id         string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Key        string `protobuf:"bytes,4,opt,name=key" json:"key,omitempty"`
	AAATokenID string `protobuf:"bytes,5,opt,name=AAATokenID" json:"AAATokenID,omitempty"`
}

func (m *CloudTokenCall) Reset()                    { *m = CloudTokenCall{} }
func (m *CloudTokenCall) String() string            { return proto.CompactTextString(m) }
func (*CloudTokenCall) ProtoMessage()               {}
func (*CloudTokenCall) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *CloudTokenCall) GetCloud() string {
	if m != nil {
		return m.Cloud
	}
	return ""
}

func (m *CloudTokenCall) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CloudTokenCall) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CloudTokenCall) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CloudTokenCall) GetAAATokenID() string {
	if m != nil {
		return m.AAATokenID
	}
	return ""
}

type CloudTokenBack struct {
	Id  string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Key string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *CloudTokenBack) Reset()                    { *m = CloudTokenBack{} }
func (m *CloudTokenBack) String() string            { return proto.CompactTextString(m) }
func (*CloudTokenBack) ProtoMessage()               {}
func (*CloudTokenBack) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *CloudTokenBack) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CloudTokenBack) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func init() {
	proto.RegisterType((*CloudAPICall)(nil), "pb.CloudAPICall")
	proto.RegisterType((*CloudAPIBack)(nil), "pb.CloudAPIBack")
	proto.RegisterType((*CloudTokenCall)(nil), "pb.CloudTokenCall")
	proto.RegisterType((*CloudTokenBack)(nil), "pb.CloudTokenBack")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CloudAPIService service

type CloudAPIServiceClient interface {
	RequestRPC(ctx context.Context, in *CloudAPICall, opts ...grpc.CallOption) (*CloudAPIBack, error)
}

type cloudAPIServiceClient struct {
	cc *grpc.ClientConn
}

func NewCloudAPIServiceClient(cc *grpc.ClientConn) CloudAPIServiceClient {
	return &cloudAPIServiceClient{cc}
}

func (c *cloudAPIServiceClient) RequestRPC(ctx context.Context, in *CloudAPICall, opts ...grpc.CallOption) (*CloudAPIBack, error) {
	out := new(CloudAPIBack)
	err := grpc.Invoke(ctx, "/pb.CloudAPIService/RequestRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CloudAPIService service

type CloudAPIServiceServer interface {
	RequestRPC(context.Context, *CloudAPICall) (*CloudAPIBack, error)
}

func RegisterCloudAPIServiceServer(s *grpc.Server, srv CloudAPIServiceServer) {
	s.RegisterService(&_CloudAPIService_serviceDesc, srv)
}

func _CloudAPIService_RequestRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloudAPICall)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudAPIServiceServer).RequestRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CloudAPIService/RequestRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudAPIServiceServer).RequestRPC(ctx, req.(*CloudAPICall))
	}
	return interceptor(ctx, in, info, handler)
}

var _CloudAPIService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CloudAPIService",
	HandlerType: (*CloudAPIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestRPC",
			Handler:    _CloudAPIService_RequestRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Li.proto",
}

// Client API for CloudTokenService service

type CloudTokenServiceClient interface {
	TokenSet(ctx context.Context, in *CloudTokenCall, opts ...grpc.CallOption) (*CloudTokenBack, error)
	TokenGet(ctx context.Context, in *CloudTokenCall, opts ...grpc.CallOption) (*CloudTokenBack, error)
}

type cloudTokenServiceClient struct {
	cc *grpc.ClientConn
}

func NewCloudTokenServiceClient(cc *grpc.ClientConn) CloudTokenServiceClient {
	return &cloudTokenServiceClient{cc}
}

func (c *cloudTokenServiceClient) TokenSet(ctx context.Context, in *CloudTokenCall, opts ...grpc.CallOption) (*CloudTokenBack, error) {
	out := new(CloudTokenBack)
	err := grpc.Invoke(ctx, "/pb.CloudTokenService/tokenSet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudTokenServiceClient) TokenGet(ctx context.Context, in *CloudTokenCall, opts ...grpc.CallOption) (*CloudTokenBack, error) {
	out := new(CloudTokenBack)
	err := grpc.Invoke(ctx, "/pb.CloudTokenService/tokenGet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CloudTokenService service

type CloudTokenServiceServer interface {
	TokenSet(context.Context, *CloudTokenCall) (*CloudTokenBack, error)
	TokenGet(context.Context, *CloudTokenCall) (*CloudTokenBack, error)
}

func RegisterCloudTokenServiceServer(s *grpc.Server, srv CloudTokenServiceServer) {
	s.RegisterService(&_CloudTokenService_serviceDesc, srv)
}

func _CloudTokenService_TokenSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloudTokenCall)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudTokenServiceServer).TokenSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CloudTokenService/TokenSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudTokenServiceServer).TokenSet(ctx, req.(*CloudTokenCall))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudTokenService_TokenGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloudTokenCall)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudTokenServiceServer).TokenGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CloudTokenService/TokenGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudTokenServiceServer).TokenGet(ctx, req.(*CloudTokenCall))
	}
	return interceptor(ctx, in, info, handler)
}

var _CloudTokenService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CloudTokenService",
	HandlerType: (*CloudTokenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "tokenSet",
			Handler:    _CloudTokenService_TokenSet_Handler,
		},
		{
			MethodName: "tokenGet",
			Handler:    _CloudTokenService_TokenGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Li.proto",
}

func init() { proto.RegisterFile("Li.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 377 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xc1, 0x6e, 0xa2, 0x50,
	0x14, 0x1d, 0x10, 0xd1, 0xb9, 0x1a, 0xc7, 0xb9, 0x99, 0x4c, 0x08, 0x69, 0x1a, 0xc3, 0xca, 0x15,
	0x0b, 0xea, 0xa2, 0xed, 0x8e, 0x5a, 0xd3, 0x9a, 0x76, 0x61, 0x68, 0x7f, 0xe0, 0x09, 0x2f, 0x86,
	0x88, 0x40, 0x01, 0x4d, 0x4c, 0x9a, 0xf4, 0x2b, 0xfa, 0xbf, 0xcd, 0xbb, 0xef, 0x81, 0xd4, 0x5d,
	0x77, 0xe7, 0x9c, 0xcb, 0x3d, 0xf7, 0x9d, 0xa3, 0xd0, 0x7f, 0x8e, 0xdd, 0xbc, 0xc8, 0xaa, 0x0c,
	0xf5, 0x7c, 0xed, 0x7c, 0xea, 0x30, 0x9c, 0x27, 0xd9, 0x3e, 0xf2, 0x57, 0xcb, 0x39, 0x4b, 0x12,
	0xb4, 0xa0, 0x57, 0xf2, 0xe2, 0x10, 0x87, 0xdc, 0xd2, 0x26, 0xda, 0xf4, 0x77, 0x50, 0x53, 0xfc,
	0x0f, 0x26, 0x0b, 0xab, 0x38, 0x4b, 0x2d, 0x9d, 0x06, 0x8a, 0x09, 0xbd, 0xe0, 0x1b, 0xa1, 0x77,
	0xa4, 0x2e, 0x99, 0x70, 0x0a, 0x85, 0xf3, 0x32, 0xb2, 0x0c, 0xe9, 0xa4, 0x28, 0xda, 0xd0, 0x27,
	0xf8, 0xc4, 0x8f, 0x56, 0x97, 0x46, 0x0d, 0xc7, 0x7f, 0xd0, 0x25, 0x6c, 0x99, 0x34, 0x90, 0x04,
	0x67, 0x60, 0xe6, 0xac, 0x60, 0xbb, 0xd2, 0xea, 0x4d, 0x3a, 0xd3, 0x81, 0x77, 0xe1, 0xe6, 0x6b,
	0xb7, 0xfd, 0x6e, 0x77, 0x45, 0xe3, 0x45, 0x5a, 0x15, 0xc7, 0x40, 0x7d, 0x6b, 0xdf, 0xc0, 0xa0,
	0x25, 0xe3, 0x18, 0x3a, 0x5b, 0x7e, 0x54, 0xb1, 0x04, 0x14, 0xc7, 0x0e, 0x2c, 0xd9, 0x73, 0x95,
	0x48, 0x92, 0x5b, 0xfd, 0x5a, 0x73, 0x1e, 0x4f, 0xb5, 0xdc, 0xb1, 0x70, 0x8b, 0x08, 0x46, 0x98,
	0x45, 0xb2, 0x93, 0x6e, 0x40, 0x58, 0xf8, 0xed, 0xca, 0x8d, 0xda, 0x15, 0x50, 0x7c, 0x15, 0xb1,
	0x8a, 0x51, 0x11, 0xc3, 0x80, 0xb0, 0xf3, 0x0e, 0x23, 0x72, 0x7a, 0xcd, 0xb6, 0x3c, 0xa5, 0x8a,
	0x9b, 0x88, 0x5a, 0x3b, 0x22, 0x82, 0x91, 0xb2, 0x5d, 0xfd, 0x14, 0xc2, 0x38, 0x02, 0x3d, 0x8e,
	0x54, 0xad, 0x7a, 0x1c, 0xd5, 0x09, 0x8c, 0x53, 0x82, 0x4b, 0x00, 0xdf, 0xf7, 0xc9, 0x7b, 0x79,
	0xaf, 0xca, 0x6c, 0x29, 0x8e, 0xd7, 0xbe, 0x4e, 0x49, 0xa4, 0xa7, 0x76, 0xee, 0xa9, 0x37, 0x9e,
	0xde, 0x02, 0xfe, 0xd4, 0xd9, 0x5f, 0xd4, 0x6f, 0xef, 0x01, 0x04, 0xfc, 0x6d, 0xcf, 0xcb, 0x2a,
	0x58, 0xcd, 0x71, 0x7c, 0xde, 0xbe, 0xfd, 0x4d, 0x11, 0x67, 0x9c, 0x5f, 0xde, 0x07, 0xfc, 0x3d,
	0x9d, 0xae, 0x8d, 0x66, 0xd0, 0xaf, 0x24, 0xaf, 0x10, 0x9b, 0xa5, 0xa6, 0x1b, 0xfb, 0x4c, 0x93,
	0x56, 0xcd, 0xd6, 0xc3, 0x4f, 0xb6, 0xd6, 0x26, 0xfd, 0xcd, 0xaf, 0xbe, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x73, 0x1a, 0xd1, 0xd9, 0xf2, 0x02, 0x00, 0x00,
}
